#!/bin/bash

function _directory_exists?()
{
	[ -n "$1" -a -d "$1" ]
}

function _file_exists?()
{
	[ -n "$1" -a -f "$1" ]
}

function _form_path()
{
	local path_root="${1%/}"
	local filename="$2"
	echo "${path_root}/${filename}"
}

function main()
{
	local script_dir="${BASH_SOURCE%/*}"
        
	# Load config
        local config_path="${script_dir}/create_profile.conf"
        _file_exists? "${config_path}" || {
                echo "ERROR: Unable to find config file ${config_path}"
                false; return
        }
        source ${config_path} || {
                echo "ERROR: Unable to load config file ${config_path}"
                false; return
        }

	# Create placeholder profile plist file
	_directory_exists? "${ITERM_PROFILE_DIR}" || {
		echo "ERROR: Export variable ITERM_PROFILE_DIR not set or not valid path"
		false; return
	}
	local profile_path="$(_form_path "${ITERM_PROFILE_DIR}" "${_PROFILE_NAME}.plist")"
	echo "INFO: Creating profile ${_PROFILE_NAME} as ${profile_path} ..."
	cat /dev/null >| "${profile_path}" || {
		echo "ERROR: Unable to create profile ${profile_path}"
		false; return
	}

	# form path to template
	local template_path="${script_dir}/profile_template.plist"
	_file_exists? "${template_path}" || {
		echo "ERROR: Unable to find profile template ${template_path}"
		false; return
	}

	# transform profile template to form profile
	echo "INFO: Transforming ${template_path} to form profile"
	envsubst<"${template_path}" > "${profile_path}"
}

main
exit $?

