#!/usr/bin/env bash

set -o errtrace	  # inherit ERR traps within functions, substs and subshells
set -o pipefail	  # fail entire pipeline
set -o nounset	  # exit on any attempt to use uninitialized variables
set -o errexit	  # exit the script if any statement returns non-true

# Rather than using dynamic paths just cd into the script directory
# This works better for linting as well
_SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$_SCRIPT_PATH" || exit 1

# Bring in the core library and enable global error handler
# No futher need to check return codes after this point ...
source ./lib/core.sh || exit 1
USE_GLOBAL_ERROR_HANDLER

function install_prequisites()
{
	msg_info "Installing prerequisites"

	# Ensure xcode command line tools are installed
	msg_info "Installing XCode CLI tools if they are missing ..."
	sudo xcode-select --install
}

function install_packages()
{
	msg_info "Installing packages ..."
	# TODO - git config
}

function main()
{
	./install/install_links || return 1;
	install_packages || return 1;
}

main
exit $?

