#!/bin/bash

echo "Creating Vagrant home directory ..." >&2
sudo mkdir -p /var/vagrant/home
sudo chmod a+rwx /var/vagrant/home

echo "Creating Vagrant clone directory ..." >&2
sudo mkdir -p /var/vagrant/clone
sudo chmod a+rwx /var/vagrant/clone

