#!/bin/bash

DEPENDS_ON exists

USE_GLOBAL_ERROR_HANDLER

function main()
{
	local reposPath
	reposPath="$1"

	cd "${reposPath}" || { false; return; }

	msg_info "Performing custom install for ${reposPath}"
	# Tern requires node.js and npm to be installed
	# The tern server is installed by running npm install in the plugin directory
	npm install
}

main "$@"
exit $?

