#!/bin/bash

DEPENDS_ON exists 

USE_GLOBAL_ERROR_HANDLER

function main()
{
	local reposPath
	reposPath="$1"

	directory_exists? "${reposPath}" ||\
		fail "Unable to local repos with path ${reposPath}"

	cd "${reposPath}" || false; return

	msg_info "Performing custom install for ${reposPath}"
	# https://valloric.github.io/YouCompleteMe/
	# Requires: cmake, mono, go, rust
	./install.py \
		--omnisharp-completer \
		--gocode-completer \
		--tern-completer \
		--racer-completer
}

main "$@" && exit 0
exit 1

