#!/bin/bash

DEPENDS_ON path \
	exists 

USE_GLOBAL_ERROR_HANDLER

function main()
{
	local pathToBundles
	local reposPath
	local reposName

	pathToBundles="/Users/$USER/.vim/bundle"
	dir_exists? "${pathToBundles}" || \
		fail "Unable to location vim bundles at ${pathToBundles}"

	for reposPath in ${pathToBundles}/*
	do
	(
		cd "${reposPath}" || continue
		msg_info "Updating $(basename "${reposPath}")"
		git submodule update --recursive

		reposName="$(git name)"
		do_per_repos_install "${reposName}"
	)
	done
}

function do_per_repos_install()
{
	local reposName
	reposName="$1"

	case "${reposName}" in
	"YouCompleteMe")
		msg_info "Performing custom install for ${reposName}"
		# https://valloric.github.io/YouCompleteMe/
		# Requires: cmake, mono, go, rust
		./install.py \
			--omnisharp-completer \
			--gocode-completer \
			--tern-completer \
			--racer-completer
	;;
	*)
		msg_info "Nothing todo for repos ${reposName}"
	esac
}

main 
exit $?
