" Enable Pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
syntax on
filetype plugin indent on

" Enbable Powerline
let pippath = $PIP_PATH . "/powerline/bindings/vim/"
" Not sure this is right ... using exec to allow me to set rtp to a variable
" Using rtp += pippath does not work
exec "set rtp+=" . pippath
" Ensure 256 color support is enabled
set t_Co=256
" Enable unicode symbols for Powerline
let g:Powerline_symbols = "fancy"

" Syntastic recommended settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
