" Enable Pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
syntax on
filetype plugin indent on

" Leader and leader actions
let mapleader = "\<Space>"
" Open a new file: <Leader>o
nnoremap <Leader>o :CtrlP<CR>
" Save file: <Leader>w
nnoremap <Leader>w :w<CR>

" Enbable Powerline
let pippath = $PIP_PATH . "/powerline/bindings/vim/"
" Not sure this is right ... using exec to allow me to set rtp to a variable
" Using rtp += pippath does not work
exec "set rtp+=" . pippath
" Ensure 256 color support is enabled
set t_Co=256
" Enable unicode symbols for Powerline
let g:Powerline_symbols = "fancy"

" Syntastic recommended settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Colorscheme
syntax enable
set background=dark
colorscheme solarized

" Setup indentation to not use hard tabs
set expandtab
set shiftwidth=2
set softtabstop=2
" Configure vim-indent-guides
let g:indent_guides_start_level=2
let g:indent_guides_guide_size=1

