#!/bin/bash

function app_exists()
{
  # command -v	: describe a command without executiing it, exit 1 if doesnt exist
  command -v "$1" >/dev/null 2>&1
}

if [ ! "$HOMEBREW_GITHUB_API_TOKEN" ]; then
  echo "Please set the HOMEBREW_GITHUB_API_TOKEN environment variable and retry" >&2
  return 1
fi

echo "Setting up file permissions to support multi-user environments" >&2
# Create account for the admistration of homebrew and add current user
if ! dseditgroup -q -o read homebrew >/dev/null 2>&1; then
  echo "Creating homebrew group ..." >&2
  sudo dseditgroup -o create homebrew
fi
if ! dseditgroup -q -o checkmember -m "$USER" homebrew >/dev/null 2>&1; then
  echo "Adding current user to homebrew group ..." >&2
  sudo dseditgroup -o edit -a "$USER" -t user homebrew
fi
echo "Setting up file permissions for homebrew ..." >&2
sudo chgrp -R homebrew /usr/local
sudo chmod -R g+w /usr/local

if ! app_exists "brew"; then
  echo "Installing Homebrew ..." >&2
  # redirect stdin away from tty to avoid any user prompts
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" </dev/null
fi

if ! brew cask --version >/dev/null 2>&1; then
  echo "Installing Cask ..." >&2
  brew install caskroom/cask/brew-cask
fi

echo "Updating Homebrew ..." >&2
brew update

echo "Checking for updates to any pre-existing formulae ..." >&2
brew upgrade

echo "Cleaning up outdated formuale ..." >&2
brew cleanup
brew cask cleanup

