#!/bin/bash

# Created default ssh keypair
# Sets up all directory and keypair permissions
# Adds to ssh-agent
# Adds to ssh config file to demonstrate the usage of multiple ssh keypairs
# Copies the default keypair public key to clipboard ready for export to github

if [ -z "$1" ]; then
  echo "Usage: ${BASH_SOURCE[0]} email-address" >&2
  exit 1
fi

echo "Creating ssh directory and setting permissions ..." >&2
mkdir -p "${HOME}/.ssh"
# drwx------
chmod 700 "${HOME}/.ssh"
echo "Done" >&2

if [ ! -f "${HOME}/.ssh/id_rsa" ]; then
  echo "Creating default ssh keypair ..." >&2
  ssh-keygen -t rsa \
    -f "${HOME}/.ssh/id_rsa" \
    -C "$1" \
    -N "" \
    -q
  if (( $? != 0 )); then
    echo "Error: unable to create default ssh keypair" >&2
    exit 1
  fi
else
  echo "Default keypair already exists - taking no action" >&2
fi

echo "Setting permissions on default keypair" >&2
# -rw-------
chmod 600 "${HOME}/.ssh/id_rsa"
# -rw-r--r--
chmod 644 "${HOME}/.ssh/id_rsa.pub"

echo "Adding default keypair to ssh-agent" >&2
ssh-add "${HOME}/.ssh/id_rsa" > /dev/null || exit 1
if (( $(ssh-add -l | grep -c "id_rsa") != 1 )); then
  echo "Error: unable to add default key to ssh-agent" >&2
  exit
fi

if [ ! -f "${HOME}/.ssh/config" ]; then
  echo "Creating ssh config file ..." >&2
  touch "${HOME}/.ssh/config"
fi

if (( $(grep -i -c "Host github.com" "${HOME}/.ssh/config") == 0 )); then
  echo "Adding entries to ssh config for default ssh keypair ..." >&2
  cat >> "${HOME}/.ssh/config" <<EOF
Host github.com
  User git
  Hostname github.com
  PreferredAuthentications publickey
  IdentitiesOnly yes
  IdentityFile ~/.ssh/id_rsa

# Example usage for using non-default keypair via a host alias
# Mapped back onto the default keypair here in this case
# $ git clone git@default-github.com:user/repos
# Then within the repos set the username and email
# $ git config user.name "<user_name>"
# $ git config user.email "<user_email>"
Host default-github.com
  User git
  Hostname github.com
  PreferredAuthentications publickey
  IdentitiesOnly yes
  IdentityFile ~/.ssh/id_rsa
EOF
fi

echo "Adding github to known_hosts ..." >&2
grep "github" "${HOME}/.ssh/known_hosts" >/dev/null 2>&1 || \
  ssh-keyscan -t -rsa github.com >> "${HOME}/.ssh/known_hosts"

echo "Copying public key to the clipboard ready to add to github ..." >&2
pbcopy < "${HOME}/.ssh/id_rsa.pub"
if (( $? != 0 )); then
  echo "Unable to copy public key to clipboard - maybe tmux or screen is running ?" >&2
  exit 1
fi

