#!/usr/bin/env bash

_SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$_SCRIPT_PATH" || exit 1

setup_seil()
{
  # As required by Seil when remapping the caps lock key:
  # Umap the caps lock key within OS X preferences
  echo "Running unmap_caps.scpt" >&2
  osascript ./unmap_caps.scpt

  # Run in Seil default
  echo "Running in Seil defaults from seil_import ..." >&2
  . ./seil_import

  # Restart Seil
  echo "Restarting Seil ..." >&2
  /Applications/Seil.app/Contents/Library/bin/seil relaunch
}

setup_karabiner()
{
  # Grant accessibility access to Karabiner
  echo "Granting accessibility access to the Karabiner AXNotifier app ..." >&2
  sudo tccutil -i org.pqrs.Karabiner-AXNotifier

  # Steps to create the plist in the first place:
  # plutil -convert xml1 -o ~/tmp/karabiner.plist ~/Library/Preferences/org.pqrs.Karabiner.plist
  echo "Running plist defaults into Karabiner from karabiner.plist ..." >&2
  defaults import org.pqrs.Karabiner ./karabiner.plist

  # Run in Karabiner defaults
  echo "Running in Karabiner defaults from karabiner_import ..." >&2
  . ./karabiner_import

  # Restart Karabina
  echo "Restarting Karabiner ..." >&2
  /Applications/Karabiner.app/Contents/Library/bin/karabiner relaunch
}

main()
{
  setup_seil || return
  setup_karabiner || return
}

main
exit $?
