#!/usr/bin/env bash

# Locate a specific file or directory in parent directories

function main() 
{
	local cwd 
	cwd=$(pwd -P 2>/dev/null || command pwd)
	while [ ! -e "${cwd}/$1" ]; do	
		# ${string%substring}
		#+ Deletes the shortest match of $substring
		#+ from the back of $string
		cwd=${cwd%/*}
		if [ ! "$cwd" ]; then break; fi
	done
	echo "$cwd"
}

cwd="$(main "$@")"
if (( $? == 0 )) && [ -n "${cwd}" ]; then
	echo "${cwd}"
	exit 0
fi

exit 1 
