#!/bin/bash

# bring in gnu getopt ( a key-only package )
PATH="$(brew --prefix)"/opt/gnu-getopt/bin:$PATH

# dry run ( debug ) mode
DRY_RUN=false

function main()
{
        local parsed_options
        local autounattend_file
        local packer_args
        
        parsed_options="$(getopt -q -n "$(basename "$0")" -o - -l dry-run -- "$@")"
        [ $? -ne 0 ] && return 1;

        # wang the parsed options back into script arguments
        eval set -- "$parsed_options"

        while true; do
                case "$1" in
                        --dry-run) DRY_RUN=true;;
                        --) break ;;
                        *) autounattend_file="$1";;
                esac
                shift # shift off the argument we have just inspected
        done
        shift # shift off the "--"

        # the arguments that are left (post the --) can then be passed to packer build
        packer_args="$*"

        echo "$autounattend_file"
        echo "$packer_args"
        if $DRY_RUN; then echo "DEBUG"; fi 
}

main "$@"
exit $?

