#!/bin/bash

# bring in gnu getopt (a keg only brew package that isnt linked by default)
PATH="$(brew --prefix)"/opt/gnu-getopt/bin:$PATH

# use -q as not interested in hearing about invalid options
# -n foo -> report errors from foo
# -o -> single character options
# + -> POSIX compliant mode ( stop an first non option )
eval set -- "$(getopt -q -n foo -o +a -- "$@")"
while test "$1" != "--"; do 
      case "$1" in
            -a) : ;;
            *) echo "$1";
      esac
      shift  # shift off the argument
done

shift  # delete the "--"
echo "remaining args are: $*"




# which we can then use to proxy a command
# eval "ls $*"

