#!/bin/bash

function exit_handler()
{
        # check the TEMPFILE variable has been set and that it points to an existing file
        if [[ ! -z "${TEMPFILE+.}" && -f "${TEMPFILE}" ]]; then
                rm -rf "${TEMPFILE}"
        fi
}

function usage()
{
        cat <<EOF
Usage: $0 <template-file> -v <variable-file> -a <unattend-file> 
EOF

        return 1
}

function main()
{
        local var_file
        local template
        local autounattend

        # non-positional arguments
        while getopts "v:a:" opt; do
                case "$opt" in 
                        v) 
                                var_file="$OPTARG"
                                ;;
                        a)
                                autounattend="$OPTARG"
                                if [ ! -f "$autounattend" ]; then
                                        echo "Unable to locate specified autounattend ${autounattend}" >& 2
                                        return 1
                                fi 
                                ;;
                        \?)
                                echo "Invalid argument: -$OPTARG" >&2
                                return 1
                                ;;
                        :)
                                echo "Option -$OPTARG requires an argument" >&2
                                return 1
                                ;;
                esac
        done

        # check required positional argument was passed
        if [ ! $(( $# - OPTIND )) -lt 1 ]; then
                usage
                return
        fi

        # use indirect expansion to get nth positional argument
        template="${!OPTIND}"

        if [ ! -f "$template" ]; then
                echo "Unable to locate specified template ${template}" >& 2
                return 1;
        fi

        if [ -z "${autounattend+.}" ]; then

                # source in any environment variables required for the transform
                if  [ -f "$HOME/.secrets/licenses" ]; then
                        # shellcheck source=/dev/null
                        source "$HOME/.secrets/licenses"
                fi
        fi
}

trap 'exit_handler' EXIT

main "$@"
exit $?

